---
title: "Open data science (IODS) course project"
author: "Mohammad Imangholiloo"
output:
  html_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 6
    theme: cosmo
    toc: yes
    toc_depth: 2
  word_document:
    toc: yes
    toc_depth: '2'
---

***

# Introduction to Open Data Science - Course Project

```{r child = "chapter1.Rmd"}
# This will include Chapter 1 (that is updated in its own file) in the document.
```
  
***

```{r child = "chapter2.Rmd"}
# This will include Chapter 2 (that is updated in its own file) in the document.
```

***

```{r child = "chapter3.Rmd"}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

***

```{r child = "chapter4.Rmd"}
# This will include Chapter 4 (that is updated in its own file) in the document.
```

***
```{r}
options(knitr.duplicate.label = "allow")
#to sovel following error (mentioned below), I put this chunk to run and solved the error:
#error: Error in parse_block(g[-1], g[1], params.src, markdown_mode) :    Duplicate chunk label 'setup', which has been used for the chunk: knitr::opts_chunk$set(echo = TRUE) Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
#insprited from: https://bookdown.org/yihui/rmarkdown-cookbook/duplicate-label.html
```


```{r child = "chapter5.Rmd"}
# This will include Chapter 5 (that is updated in its own file) in the document.
```

***

```{r child = "chapter6.Rmd"}
# This will include Chapter 4 (that is updated in its own file) in the document.
```

**The END**